/*
CREATED: 15/12/2016
MODIFIED: 11/01/2017
MODEL: ORACLE 11G RELEASE 1
DATABASE: ORACLE 11G RELEASE 1
*/


-- CREATE SEQUENCES SECTION -------------------------------------------------

CREATE SEQUENCE "MOTOR"."SEQ_CLIENTE"
 INCREMENT BY 1
 START WITH 6
 MAXVALUE 9999
 NOMINVALUE
 NOCACHE
/

CREATE SEQUENCE "MOTOR"."SEQ_COCHE"
 INCREMENT BY 1
 START WITH 8
 MAXVALUE 9999
 NOMINVALUE
 NOCACHE
/

-- CREATE TABLES SECTION -------------------------------------------------

-- TABLE CLIENTE

CREATE TABLE "CLIENTE"(
  "CLIENTE_ID" NUMBER NOT NULL,
  "NOMBRE" VARCHAR2(30 ) NOT NULL,
  "APELLIDO1" VARCHAR2(30 ) NOT NULL,
  "APELLIDO2" VARCHAR2(30 ),
  "EMAIL" VARCHAR2(30 ) NOT NULL,
	CONSTRAINT "CHECK_CONSTRAINT_EMAIL" CHECK (EMAIL LIKE ('%@%')),
  CONSTRAINT "EMAIL_MINIMO" CHECK (LENGTH(EMAIL) > 7),
  "TELEFONO" CHAR(9 ) NOT NULL
        CONSTRAINT "CHECK_CONSTRAINT_TELEFONO" CHECK (SUBSTR(TELEFONO,0,1) IN (6,9)),
  "DNI" CHAR(9 ) NOT NULL
)
/

-- ADD KEYS FOR TABLE CLIENTE

ALTER TABLE "CLIENTE" ADD CONSTRAINT "KEY1" PRIMARY KEY ("CLIENTE_ID")
/

ALTER TABLE "CLIENTE" ADD CONSTRAINT "DNI" UNIQUE ("DNI")
/

ALTER TABLE "CLIENTE" ADD CONSTRAINT "EMAIL" UNIQUE ("EMAIL")
/

ALTER TABLE "CLIENTE" ADD CONSTRAINT "TELEFONO" UNIQUE ("TELEFONO")
/

-- CREATE TRIGGERS FOR TABLE CLIENTE


CREATE OR REPLACE TRIGGER TALLER_ABIERTO_CLIENTE
  AFTER INSERT OR UPDATE ON CLIENTE
    FOR EACH ROW
BEGIN
    IF (TO_CHAR(SYSDATE,'HH24') BETWEEN 22 AND 8 ) THEN
      RAISE_APPLICATION_ERROR(-20004,'EL TALLER ESTá CERRANDO ENTRE LAS 22:00 Y LAS 08:00');  
    END IF;
END;
/

CREATE OR REPLACE TRIGGER EMAIL_BIEN_ESCRITA 
BEFORE INSERT OR UPDATE OF EMAIL ON CLIENTE 
FOR EACH ROW
BEGIN
  IF (substr(lower(:NEW.email),length(:NEW.email)-3,length(:NEW.email)) not like '%.com%' AND substr(lower(:NEW.email),length(:NEW.email)-2,length(:NEW.email)) not like '%.es%') THEN
    RAISE_APPLICATION_ERROR(-20005,'EL EMAIL DEBE ACABAR POR .COM O .ES');
  END IF;
END;
/


-- TABLE COCHE

CREATE TABLE "COCHE"(
  "COCHE_ID" NUMBER NOT NULL,
  "MARCA" VARCHAR2(30 ) NOT NULL,
  "MODELO" VARCHAR2(30 ) NOT NULL,
  "MATRICULA" CHAR(8 ) NOT NULL,
  "ITV" DATE NOT NULL,
  "CLIENTE_ID" NUMBER NOT NULL
)
/

-- ADD KEYS FOR TABLE COCHE

ALTER TABLE "COCHE" ADD CONSTRAINT "KEY2" PRIMARY KEY ("COCHE_ID","CLIENTE_ID")
/

ALTER TABLE "COCHE" ADD CONSTRAINT "MATRICULA" UNIQUE ("MATRICULA")
/

-- CREATE TRIGGERS FOR TABLE COCHE


CREATE OR REPLACE TRIGGER ITV_PASADA
  AFTER INSERT OR UPDATE OF ITV ON COCHE
    FOR EACH ROW
    WHEN (NEW.ITV < SYSDATE OR OLD.ITV < SYSDATE)
BEGIN
    RAISE_APPLICATION_ERROR(-20002,'EL COCHE TIENE QUE TENER PASADA LA ITV');  
END;
/


CREATE VIEW "VW_CLIENTE" AS
SELECT "CLIENTE_ID", "NOMBRE", "APELLIDO1", "APELLIDO2", "EMAIL", "TELEFONO", "DNI"
FROM "CLIENTE"
/

CREATE VIEW "VW_COCHE" AS
SELECT "COCHE_ID", "MARCA", "MODELO", "MATRICULA", "ITV", "APELLIDO2", "CLIENTE"."CLIENTE_ID", "NOMBRE", "APELLIDO1", "EMAIL", "TELEFONO", "DNI"
FROM "COCHE", "CLIENTE"
WHERE CLIENTE.CLIENTE_ID=COCHE.CLIENTE_ID
/

-- CREATE RELATIONSHIPS SECTION ------------------------------------------------- 

ALTER TABLE "COCHE" ADD CONSTRAINT "RELATIONSHIP1" FOREIGN KEY ("CLIENTE_ID") REFERENCES "CLIENTE" ("CLIENTE_ID")
/

