/*
Created: 30/01/2017
Modified: 30/01/2017
Model: Oracle 11g Release 1
Database: SQLite 3.7
*/


-- Drop triggers for tables section -------------------------------------------------

DROP TRIGGER ITV_PASADA_INSERT;
DROP TRIGGER ITV_PASADA_UPDATE;
DROP TRIGGER TALLER_ABIERTO_CLIENTE_INSERT;
DROP TRIGGER TALLER_ABIERTO_CLIENTE_UPDATE;
DROP TRIGGER CAMPO_VACIO_CLIENTE_INSERT;
DROP TRIGGER CAMPO_VACIO_CLIENTE_UPDATE;




-- Drop views section --------------------------------------------------- 

DROP VIEW VW_CLIENTE;
DROP VIEW VW_COCHE;

-- Drop tables section ---------------------------------------------------

DROP TABLE COCHE;
DROP TABLE CLIENTE;


